### ISSUE TITLE
"Uses temp file on upload?" 기능이 remote의 파일을 지워버렸어!!!

### ISSUE THREAD

**Issue by gusqlslee** [satiromarra/vscode-sftp#16]
"Uses temp file on upload?"를 "YES" 로 사용할 경우 간헐적으로 수정하고 있는 파일을 삭제하고 있어!
확인을 못했다면 중요한 파일을 날릴뻔 했어! lol
일단은 "NO"로 설정하고 사용해야 할 것 같아!

![image](https://user-images.githubusercontent.com/48116297/225811294-2108a3f3-d308-4f0b-9814-9fa27d77e180.png)

**Comment by satiromarra** [comment]
@gusqlslee English please, The translator shows me contradictory information.

**Comment by satiromarra** [comment]
@gusqlslee 
Can you show me some information from the sftp log during the file saving process?

**Comment by satiromarra** [comment]
@gusqlslee 
possibly the problem is due to the combination of different configuration options:
Upload file on save: true
Uses temp file on upload: true
Watcher Settings -> Auto upload: true

The Watchers Settings, is analyzing the modified files and when you make a change to a file it is uploaded twice, first it is uploaded normally with "tempFile" and then it is uploaded by "watcher" which does not find the remote file.

Set the Watcher Settings -> Auto upload: false
